### ISSUE TITLE
From the spec to JavaDocs... or not

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/libSBOLj#103]
The following paragraphs were removed the spec, with the note that somebody working on libSBOLj should decide whether anything got put into the JavaDocs, or if it was redundant:

> Within an implementing Object-Oriented (OO) API, SBOL properties should be mapped to member accessors that are similarly named and that return idiomatic representations of these properties. For example, a Java implementation would use common Java idioms. In this case, the member accessor for an optional SBOL property could return a Java primitive value, Java object, or null, while the accessor for a multi-valued SBOL property could return a Java \external{Collection}. In general, OO member accessors for multi-valued SBOL properties should never return null.

> As another example, a relational implementation of the SBOL API would store the properties and associations a mixture of data fields and references via foreign keys. The fields in individual tables will correspond to the `arrowhead' end of an association (in reverse to the direction in the RDF and OO representations), and the name may be modified to reflect this change in directionality. For example, the \sbol{sequence} association between a \sbol{ComponentDefinition} and \sbol{Sequence} would be represented by a foreign key field on the \sbol{Sequence} table that references a row in the \sbol{ComponentDefinition} table, and it may be named \external{sequenceOf}.

**Comment by cjmyers** [comment]
Hmm, sounds more a like a design specification than documentation.
