### ISSUE TITLE
createSequenceAnnotation for a Cut location fails 

### ISSUE THREAD

**Issue by goksel** [SynBioDex/libSBOLj#114]
When you call the method below it fails:
promoter.createSequenceAnnotation("cut", 10);

This method call works:
promoter.createSequenceAnnotation("cut", 10, OrientationType.INLINE);

The full example: 
               String prURI="http://partsregistry.org";
		SBOLDocument document = new SBOLDocument();		
		document.setDefaultURIprefix(prURI);
		document.setTypesInURIs(true);
		ComponentDefinition promoter = document.createComponentDefinition(
				"BBa_J23119",
				"",
				new HashSet<URI>(Arrays.asList(ComponentDefinition.DNA)));
		promoter.addRole(SequenceOntology.PROMOTER);
		promoter.addRole(URI.create("http://identifiers.org/so/SO:0000613"));
				
		promoter.setName("J23119 promoter");
		promoter.setDescription("Constitutive promoter");	
		promoter.setWasDerivedFrom(URI.create("http://partsregistry.org/Part:BBa_J23119"));
	  
		document.setDefaultURIprefix(prURI);	
		Sequence seq=document.createSequence(
				"BBa_J23119",
				"",
				 "ttgacagctagctcagtcctaggtataatgctagc", 
				URI.create("http://www.chem.qmul.ac.uk/iubmb/misc/naseq.html")
				);
		seq.setWasDerivedFrom(URI.create("http://parts.igem.org/Part:BBa_J23119:Design"));
		promoter.addSequence(seq.getIdentity());	
		
		promoter.createSequenceAnnotation("cut", 10);
		//promoter.createSequenceAnnotation("cut", 10, OrientationType.INLINE);
				
		
		SBOLWriter.write(document,(System.out));

**Comment by cjmyers** [comment]
Fixed.
