### ISSUE TITLE
Custom annotation namespaces are not correctly added

### ISSUE THREAD

**Issue by goksel** [SynBioDex/libSBOLj#125]
When representing a term in RDF, there must be a separator between a namespace URI and a local term. Currently, libSBOLj allows writing document without any separator.

For the example below prURI should be, for example,  "http://partsregistry.org/" or ""http://partsregistry.org#"

Full example:
String prURI="http://partsregistry.org";
String prPrefix="pr";	
SBOLDocument document = new SBOLDocument();		

document.setDefaultURIprefix(prURI);	
document.setTypesInURIs(true);

document.addNamespace(URI.create(prURI) , prPrefix);

ComponentDefinition promoter = document.createComponentDefinition(
		"BBa_J23119",
		"",
		new HashSet<URI>(Arrays.asList(URI.create("http://www.biopax.org/release/biopax-level3.owl#DnaRegion"))));
promoter.addRole(SequenceOntology.PROMOTER);
promoter.setName("J23119");
promoter.setDescription("Constitutive promoter");	

promoter.createAnnotation(new QName(prURI, "group", prPrefix),
				"iGEM2006_Berkeley");	
		
SBOLWriter.write(document,(System.out));

And the result:
<?xml version="1.0" ?>
<rdf:RDF xmlns:pr="http://partsregistry.org" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:prov="http://www.w3.org/ns/prov#" xmlns:sbol="http://sbols.org/v2#">
  <sbol:ComponentDefinition rdf:about="http://partsregistry.org/cd/BBa_J23119">
    <sbol:persistentIdentity rdf:resource="http://partsregistry.org/cd/BBa_J23119"/>
    <sbol:displayId>BBa_J23119</sbol:displayId>
    <pr:group>iGEM2006_Berkeley</pr:group>
    <dcterms:title>J23119</dcterms:title>
    <dcterms:description>Constitutive promoter</dcterms:description>
    <sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#DnaRegion"/>
    <sbol:role rdf:resource="http://identifiers.org/so/SO:0000167"/>
  </sbol:ComponentDefinition>
</rdf:RDF>

**Comment by cjmyers** [comment]
To clarify, are you wanting “addNamespace” to require a separator at the end?  If so, I assume “/, #, :”, correct?

Chris

**Comment by goksel** [comment]
I'm not sure about this now! I checked the resulting RDF  and it is still valid! Although, the resulting property URIs are not ideal. For the example that I gave above the full URI for the term would be "http://partsregistry.orggroup". We can discuss this a bit more maybe? Shall we close this issue without doing anything for now?

**Comment by cjmyers** [comment]
I think it is fine to require the “addNamespace” method to have a delimiter.  Seems useful.  Shall I go ahead and add that?  What delimiters do we want to allow?

**Comment by cjmyers** [comment]
Actually, we don't have any syntax checking on namespace URI.   What form is it allowed to take?  Same as our URI prefix regular expression?
