### ISSUE TITLE
removeLocation(Location) and clearLocations in SequenceAnnotation should consider the "1 or many" relation

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#131]
Since SequenceAnnotation are required to have 1 or many Location instances, these two methods should make sure not to remove all Location instances.

**Comment by cjmyers** [comment]
That is correct.  I've made clearLocations not public, and I changed remove location to throw exception if you try to remove the last one.  Please check and update comments.

**Comment by zgzn** [comment]
Fixed. Closing.
