### ISSUE TITLE
sbol-11406, SequenceConstraints should also have a constructor to have a URI for restriction types. 

### ISSUE THREAD

**Issue by goksel** [SynBioDex/libSBOLj#142]

**Comment by cjmyers** [comment]
This will be a very significant change, and it may break people’s code.  As per your earlier request, we changed all these fields from URIs to Enumerated Types.  This means that it is not possible to store an arbitrary URI as a restriction type.  The only way I can see to fix this is to change the type back to URI.  However, then it seems odd to me to have both an enumerated type and URI interface.  In other places, we only have one or the other.  How important is this?  Are we really missing important restriction types?  Can’t I just add the missing types in as additional enumerated types?  This would be much simpler.
