### ISSUE TITLE
Implement equals and hashcode methods in NamedProperty

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#144]
The Annotation class implements equal and hatched methods. This equals method requires comparison of two "value" fields owned two different Annotation instances. Since the "value" field in Annotation is type uk.ac.ncl.intbio.core.datatree.NamedProperty, then the corresponding equals and hatched methods in this class needs to be implemented.

**Comment by cjmyers** [comment]
We might be able to use the get methods to get the parts out and implement equals locally in Annotation.  Not sure about hashcode.

**Comment by cjmyers** [comment]
I've attempted to do this in the Annotation class.  Needs to be checked.
