### ISSUE TITLE
createCopy() for Sequence and Collection do not copy Name and Description

### ISSUE THREAD

**Issue by EGC1995** [SynBioDex/libSBOLj#192]
The problem is that the method is calling the wrong constructor. The deepCopy() method in Sequence is calling: Sequence(Sequence sequence) and this constructor calls TopLevel(URI identity). Instead this constructor should be called: TopLevel(TopLevel toplevel). A similar problem exists for Collection.

**Comment by zgzn** [comment]
These have been fixed. Closing.
