### ISSUE TITLE
Unable to Set All Fields in SBOL Objects

### ISSUE THREAD

**Issue by ckmadsen** [SynBioDex/libSBOLj#199]
I'm trying to rebuild an SBOL document from some RDF that I downloaded from my RDF triplestore.  The SBOL document was previously uploaded to the repository and needs to be able to roundtrip to return the very same document when downloaded.  The issue I'm having is that I cannot set all of the fields for each SBOL object, especially those that involve URIs such as persistentId.  As such, I'm unable to ensure that the document I am building matches the document that was originally uploaded.  Is there any way to add the ability to set all of the fields for each object?

**Comment by cjmyers** [comment]
These set methods do exist, but they are package private.  They are package private to prevent users of the library from being able to create non-compliant URIs.  The methods exist because we do allow non-compliant SBOL documents to be read.

The simplest solution that I can think of would be to put your RDF triplestore read function into libSBOLj itself.  You could perhaps add this as a new read method to SBOLReader and write method to SBOLWriter.  It may perhaps be useful to others.    

Will this work for you?

**Comment by ckmadsen** [comment]
That is certainly an option.  It, however, doesn't feel like very good separation of code to include a method that will be making SPARQL queries to produce SBOL right in the library, especially when others might not organize their data the same way making the queries I do meaningless to them.

I would really prefer having access to the private methods you mentioned.  If this doesn't work for you though, I can go ahead and write new read and write methods for libSBOLj.

**Comment by cjmyers** [comment]
I think perhaps I misunderstand your goal.  I agree we don’t want SPARQL queries support in the library.  I thought you wanted simply to be able to read SBOL in RDF triplestore form into the data model.  This I think would be useful to have in the library.  Are these not separable somehow?  

Chris

**Comment by ckmadsen** [comment]
I see.  Yes, it would be possible to create a method that takes in an RDF model object and creates an SBOL file from it.  I have never done it the other way, but it should be possible to create an RDF model object from SBOL as well.  The only issue I see with this is that there are several RDF libraries to choose from and not everyone will be using the same one and may, therefore, be unable to use the method unless they convert to the model we choose.  I believe that I am using one of the more well known libraries though.

I can start working on this next week.  How does that sound to you?

**Comment by cjmyers** [comment]
It might be good to have a chat about this before you start.  I don’t think you need any RDF libraries.  The data-core library developed by Goksel and Matthew, I think, can be made to work.  If you have a look at our SBMLReader code, this may clue you in a bit.  My understanding is that your RDF triple SBOL format would simply have things scattered around more.  Do you have a simple example you can send me?  

The biggest challenge I see is that our constructors currently require all required fields, so you may not be able to simply parse and convert things in the order received.  You might need to do a bit of scrambling around to extract all the information about each top level object than creating the object. 

When is a good day for you to discuss this?

Chris

**Comment by cjmyers** [comment]
I think chatting about this is a good idea.  I’m available early next week.  I have also included Matthew and Goksel on the email as they might want to join the discussion.  What time Monday or Tuesday works for you guys?

Cheers,

Curtis

**Comment by cjmyers** [comment]
Closing this issue as we are adding RDF triple store read support to address this under a different issue.
