### ISSUE TITLE
Improved usage of continuous integration

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#207]
Should make use of continuous integration with applications using SBOL as well as libSBOLj.

**Comment by jakebeal** [comment]
We also should have nightly builds, in order to rapidly detect problems caused by changes in the underlying dependencies.

**Comment by cjmyers** [comment]
Apparently travis-ci does not have this feature, but there is a service that does:

https://nightli.es <https://nightli.es/>

I believe I have setup nightly runs using this service.
