### ISSUE TITLE
Create a how to use annotations document

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#211]
A document that explains how to use genetic top levels and annotations.

**Comment by cjmyers** [comment]
Added to getting started documents.  Meher/Michael: please read it over and provide feedback.

**Comment by michael13162** [comment]
I read through it and it looks good.  To be very nit picky, I don't always understand the indentation choices.  It seems like there is enough room to combine lines 41, 42, and 47, 48, and 49, 50.  Also, sometimes the arguments are given a new line, but sometimes they aren't (33-36).

**Comment by zgzn** [comment]
I assume your line numbers refer to the getting_started.tex on the
"develop" branch, right? Note that the file on "master" branch is still the
old version, and you should read the one on "develop" if you did not.

Line indentation in the text only exists when a new paragraph, except the
first one, under a section or a subsection heading in the compiled file,
i.e. howto.pdf. The indentation or line breaks in the source file
getting_started.tex do not matter that much. After all, the user should
read the produced pdf file.

As for line indentation in the Java code snippets, I mostly put one
argument of a method call in a separate line, if all arguments of a method
call do not fit into one line. This is just for clear representation.

I hope I answered your questions. Thanks for the comments.



On Mon, Dec 7, 2015 at 4:40 PM, michael13162 <notifications@github.com>
wrote:

> I read through it and it looks good. To be very nit picky, I don't always
> understand the indentation choices. It seems like there is enough room to
> combine lines 41, 42, and 47, 48, and 49, 50. Also, sometimes the arguments
> are given a new line, but sometimes they aren't (33-36).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SynBioDex/libSBOLj/issues/211#issuecomment-162706383>.
>



-- 
Zhen Zhang

**Comment by michael13162** [comment]
Yup, I goofed.  Guilty as charged; I was on the wrong branch.  I already read and made comments on this document when Zhen emailed me the pdf though.

**Comment by cjmyers** [comment]
Done
