### ISSUE TITLE
Deal with redundant precedes in SBOL 1.1 files

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#212]
Hierarchy in SBOLDesigner produces SBOL 1.1 files with extra precedes relationships which are disallowed.  We may want to have a mode to drop these to allow import of these files.

**Comment by jakebeal** [comment]
Can you please give an example of what you mean by "extra precedes relationships which are disallowed"?  I am not sure what you mean, since to the best of me knowledge we are allowed to have as many precedes relationships as we want, even duplicates or ones with inconsistent implications.

**Comment by cjmyers** [comment]
My recollection was you could have a bioStart and bioEnd OR a precedes but not both.  Below is output from SBOLDesigner.  You can see about halfway down that there is both a precedes and a bioStart and bioEnd.  If I’m wrong, and this is legal, then it is a bug in libSBOLj 2.  If I’m write, then it is a bug in libSBOLj 1 (and SBOL Designer) to allow this, but we still might want to make libSBOLj 2 accept it.  

Chris


<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:sbol="http://sbols.org/v1#"
	xmlns:sublime="http://clarkparsia.com/sublime#"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
<sbol:DnaComponent rdf:about="urn:d40dfc96-f38d-4b6d-aa21-ba3ae81e2c70">
	<sbol:displayId>Unnamed</sbol:displayId>
	<sbol:dnaSequence>
		<sbol:DnaSequence rdf:about="urn:7c72c3dc-080a-4e00-8657-20fe26b5605a">
			<sbol:nucleotides>acgtagct</sbol:nucleotides>
		</sbol:DnaSequence>
	</sbol:dnaSequence>
	<sbol:annotation>
		<sbol:SequenceAnnotation rdf:about="urn:ab3885a7-514d-4ccd-bc6d-b0821cd8efd6">
			<sbol:bioStart>1</sbol:bioStart>
			<sbol:bioEnd>8</sbol:bioEnd>
			<sbol:strand>+</sbol:strand>
			<sbol:subComponent>
				<sbol:DnaComponent rdf:about="urn:f8a03f37-c038-4357-b6ef-0f056068dd1c">
					<sbol:displayId>Gen</sbol:displayId>
					<sbol:name></sbol:name>
					<sbol:description></sbol:description>
					<sbol:dnaSequence>
						<sbol:DnaSequence rdf:about="urn:ccf0a0fd-d7df-4e48-bee5-2234dfc3dbca">
							<sbol:nucleotides>acgtagct</sbol:nucleotides>
						</sbol:DnaSequence>
					</sbol:dnaSequence>
					<sbol:annotation>
						<sbol:SequenceAnnotation rdf:about="urn:8d87e6d5-2ad4-45b1-b65b-76294b597366">
							<sbol:precedes rdf:resource="urn:7778e28b-a4e6-4cbe-a8ea-712f4e8d53b1"/>
							<sbol:bioStart>1</sbol:bioStart>
							<sbol:bioEnd>4</sbol:bioEnd>
							<sbol:strand>+</sbol:strand>
							<sbol:subComponent>
								<sbol:DnaComponent rdf:about="urn:8c76a850-ef7e-406f-9092-72433cac3e80">
									<sbol:displayId>Pro</sbol:displayId>
									<sbol:name></sbol:name>
									<sbol:description></sbol:description>
									<sbol:dnaSequence>
										<sbol:DnaSequence rdf:about="urn:9f1efb6b-ceb1-4db8-b8cb-c52e999d901a">
											<sbol:nucleotides>acgt</sbol:nucleotides>
										</sbol:DnaSequence>
									</sbol:dnaSequence>
									<rdf:type rdf:resource="http://purl.obolibrary.org/obo/SO_0000167"/>
								</sbol:DnaComponent>
							</sbol:subComponent>
						</sbol:SequenceAnnotation>
					</sbol:annotation>
					<sbol:annotation>
						<sbol:SequenceAnnotation rdf:about="urn:7778e28b-a4e6-4cbe-a8ea-712f4e8d53b1">
							<sbol:bioStart>5</sbol:bioStart>
							<sbol:bioEnd>8</sbol:bioEnd>
							<sbol:strand>+</sbol:strand>
							<sbol:subComponent>
								<sbol:DnaComponent rdf:about="urn:fcf40a37-9e5b-4584-90cf-7c54252ca47d">
									<sbol:displayId>CDS</sbol:displayId>
									<sbol:name></sbol:name>
									<sbol:description></sbol:description>
									<sbol:dnaSequence>
										<sbol:DnaSequence rdf:about="urn:e150a76b-e96a-48b6-b3e8-3f4982af45cd">
											<sbol:nucleotides>agct</sbol:nucleotides>
										</sbol:DnaSequence>
									</sbol:dnaSequence>
									<rdf:type rdf:resource="http://purl.obolibrary.org/obo/SO_0000316"/>
								</sbol:DnaComponent>
							</sbol:subComponent>
						</sbol:SequenceAnnotation>
					</sbol:annotation>
					<rdf:type rdf:resource="http://purl.obolibrary.org/obo/SO_0000110"/>
				</sbol:DnaComponent>
			</sbol:subComponent>
		</sbol:SequenceAnnotation>
	</sbol:annotation>
</sbol:DnaComponent>

</rdf:RDF>

**Comment by cjmyers** [comment]
Ok, looked up SBOL 1.1 spec.  This is legal, but libSBOLj 2.0 is not handling it correct.  It is a bug in libSBOLj 2.0.

**Comment by cjmyers** [comment]
Ok, I've done a bit more debugging, and the problem appears to be that SBOLDesigner creates precedes relationships between SA in different DNA components.  I don't think this is explicitly illegal in SBOL 1.1, but it is illegal in SBOL 2.0 (see rule sbol-11403 and sbol-11405).  These rules state that the subject and object must be components with the CD that contains the SC.  For example,

CD top
  Comp AA instance of A
  Comp BB instance of B
CD A
  Comp W
  Comp X
  SC W precedes X
  SC X precedes Y
CD B
  Comp Y
  Comp Z
  SC Y precedes Z

This is illegal in SBOL 2.0, since object of SC X precedes Y is not a component within CD A.  To make this legal, the precedes should be move to CD top, namely SC AA precedes BB would result in the same ordering.

Now, the question is how should we handle this issue in the conversion code in the library.  Options:
1) Drop precedes that reference SA's that are not part of the current DNA component. (easy, but loses information, basically calling this invalid retroactively)
2) Attempt to lift the precedes relationship up to the higher level that instantiates both the subject and object.  (difficult to implement, especially since this higher level does not have to exist, so it might need to be created and might not be exactly what is intended in all cases)
3) Add a component reference to the CD that is object of the precedes, then if there is a higher level that includes both CDs that includes subject/object, then use mapsTo to indicate that the instances are the same in both CDs (difficult to implement, likely closest to intended)

I think I'm leaning towards option 3 as I think it is the most accurate conversion.

Chris

**Comment by jakebeal** [comment]
Using a precedes to link between two different DnaComponents is **illegal** in SBOL 1.1 as well, though it was not spelled out as clearly.  The relevant line in the specification is (emphasis added):

> The precedes relation specifies the relative order of SequenceAnnotations *for a given DnaComponent.*

It's easy to see how somebody might overlook this, but it's there in the spec.  Thus, my feeling is:
1. The bug is in SBOLDesigner, not in libSBOLj2
2. libSBOLj2 should still have the ability to detect and report errors of this type (which maybe it's doing right now already?)

**Comment by cjmyers** [comment]
Interesting.  Yes libsbolj 2 reports the error.  This yet another fail of libsbolj 1 to prevent invalid SBOL files being created.  Given this I think support to correct in libsbolj should be possible when selected by the user like we are doing for duplicate URIs.

If we implement this, should we take option one to drop which is simplest but lossy with idea it was wrong to include?  Or should we take option 3 to try to capture the tools intent in proper SBOL?  Or should library support all and user selects between error, drop, or fix?

Chris

**Comment by jakebeal** [comment]
My inclination would be to support all, and let the user select between error, drop, and fix.  Drop and fix should definitely produce warnings of some sort, though.

**Comment by cjmyers** [comment]
Currently, the library throws exceptions on warnings.   The library has no mechanism for warnings and printing to screen is not very flexible.  I’ve logged a new issue to create a messages element to SBOLDocument that can be updated with warnings/non-fatal errors during reading or validating.  This can then be processed and presented to the user in appropriate form by the user of the library.

**Comment by cjmyers** [comment]
Well, a bit more analysis reveals this was actually not an error created by SBOLDesigner but rather some file editing that was done to manually to reorganize the file.  Although SBOLDesigner did not create the erroneous precedes, it did not complain about it or remove it.  In general, if you save with undefined sequences, you get precedes but when you later add sequences, they are not removed.  This is perhaps an SBOLDesigner bug but not a catastrophic one as this is not technically illegal, I believe.  So, although libSBOLj 1.0 does not appear to complain about precedes between SA's in different DNA components, it does not appear that this is created by SBOL Designer, so perhaps this is a bit lower priority now.

**Comment by cjmyers** [comment]
Since I'm not aware of any tool actually creating this problem, but it was created by hand edits, and it was caught as an error by libSBOLj 2, I'm closing this.
