### ISSUE TITLE
instantiation of SBOL v2.0 classes

### ISSUE THREAD

**Issue by eoberortner** [SynBioDex/libSBOLj#229]
Currently, SBOL v2.0 objects can only be created via a SBOLDocument.
Example:
SBOLDocument doc = new SBOLDocument();
doc.createSequence();

If somebody wants to utilize the SBOL v2.0 data model in a tool, then they must create an SBOLDocument in order to instantiate classes. It'll be nice to create objects directly too.

**Comment by cjmyers** [comment]
Could you perhaps explain in what situations you need to create objects that are not assigned to an SBOLDocument?  I'm not sure why these are useful, as they certainly need to be assigned to a document eventually.

If this is needed, I would prefer to only make public the constructors for TopLevel objects.  Would this be okay?

Also, I would like the form of the constructor to be:

Sequence sequence = new Sequence(URIprefix, displayId, version);

Is this okay?

Finally, I will also need to make public the addCollection, addSequence, etc. methods in SBOLDocument, or you cannot add these to a document.

**Comment by eoberortner** [comment]
Hi,

sorry for the late response!

> Could you perhaps explain in what situations you need to create objects that are not assigned to an SBOLDocument? I'm not sure why these are useful, as they certainly need to be assigned to a document eventually.
> 
when using SBOL as an internal data-model and utilizing libSBOLj therefore. 

currently any object of an SBOL class must be instantiated via the SBOLDocument factory methods. 
we’ve integrated the factory methods in order to verify constraints up front when instantiating the SBOL data model. 

> Sequence sequence = new Sequence(URIprefix, displayId, version);
> 
> Is this okay?
> 
> Finally, I will also need to make public the addCollection, addSequence, etc. methods in SBOLDocument, or you cannot add these to a document.
> 

That sounds fine by me!

However, we should provide access to the constructors for all classes (not only for Sequence).

What do others think?

Thanks,
Ernst

**Comment by cjmyers** [comment]
Sequence was only meant as an example.  We would provide these for all TopLevel classes.  I prefer not to do this for child classes as they have no meaning outside of their corresponding TopLevel class.

Chris

**Comment by cjmyers** [comment]
This is now done and checked into the develop branch.  Namely, there are now public constructors for each top level object.  There are also public add methods to add these objects into SBOL documents.

**Comment by cjmyers** [comment]
Removed public on the add top level methods because this would allow multiple SBOL Document to point to the same object in memory which is problematic.  To copy an object into a document, one must use createCopy method instead to make sure the memory for the object is distinct in each document.
