### ISSUE TITLE
Validation of valid nucleotides

### ISSUE THREAD

**Issue by eoberortner** [SynBioDex/libSBOLj#230]
When setting the elements of a sequence (e.g. the nucleotides of a DNA sequence), then the library does not support validating that the sequence contains only valid elements (e.g. A,C,G,T for DNA sequences).

**Comment by cjmyers** [comment]
I've added validation for DNA/RNA/Protein sequences using these patterns:
	
	private static final String IUPAC_DNA_PATTERN = "([ACGTURYSWKMBDHVN\\-\\.]*)";	
	private static final String IUPAC_PROTEIN_PATTERN = "([ABCDEFGHIKLMNPQRSTVWXYZ]*)";

Please confirm that they look good to you.  Also, several examples we have use lower case, so I convert to upper case before checking the sequence.  Is this okay or should lower case be marked as incorrect?  If incorrect, likely legacy SBOL 1.1 will need to have case changed automatically during conversion.

Finally, I have not added check for SMILES encoding yet.  Does anyone have or know where I can get a java pattern matcher expression for this?  Seems a bit involved.

Chris

**Comment by cjmyers** [comment]
You won't be able to parse smiles with a regex. You need a full grammar. It isn't a complex one though - I've written the library.

https://github.com/drdozer/opensmiles

There's a Java class in there showing how to use it called TestStrings.java

Matthew

**Comment by cjmyers** [comment]
Added open smiles parser check now.
