### ISSUE TITLE
Ignore letter case of file type string in write methods in SBOLWriter

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#235]
For write methods that take a file type string, they only recognize all upper case strings of "JSON" and "TURTLE". If "Json" or "Turtle" is used, these write methods create output in the default RDF/XML format.

**Comment by cjmyers** [comment]
Actually I don't want the user passing a string, they should use the SBOLReader.JSON and .RDF and .TURTLE constants, in case we change them.
