### ISSUE TITLE
createComponentDefinition should have a singleton-type variant

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/libSBOLj#243]
In a vast number of usages, createComponentDefinition is likely to be called with a single type, rather than multiple types, in a set.  

We should have thus have convenience variants that take a single URI rather than a Set<URI>. The routines will just be simple wrappers that put the URI in a new set and call the standard variant.  

This will simplify usage and provide less opportunities for error in this common case.

**Comment by jakebeal** [comment]
Same for other create routines that assume a set when it will very often be a singleton, such as ModuleDefinition.createInteraction.

**Comment by cjmyers** [comment]
This is done.
