### ISSUE TITLE
Add code to throw SBOL validation exceptions for these SBOL document rules

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#302]
10102, 10103, 10104.
Both 10103 and 10104 are checked, but are not perfectly implemented.  Namely, if you don’t have name/description fields, you don’t need dcterms, but it is currently always required.

**Comment by cjmyers** [comment]
It is likely not possible to check this perfectly in libSBOLj.  Right now it is requiring them to be present which is likely incorrect.  They do not need to be there if they are not used.  However, if they are used and not present, then the parser will complain currently.

**Comment by cjmyers** [comment]
I think I did get these to work by catching parser exceptions.

**Comment by cjmyers** [comment]
They have been removed.  Closing.
