### ISSUE TITLE
Add code to throw SBOL validation exceptions for these rules for Identified objects

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#303]
10201, 10214

**Comment by cjmyers** [comment]
I'm not sure if this can be checked in libSBOLj as I think the parser will catch them.

**Comment by cjmyers** [comment]
I fixed 10201 by catching the error from the parser.  Namely, the cast exception that cannot cast to identifiable document.  Not sure what else might cause this error.
I fixed 10214 by making this an error when the namespace for the annotation is not provided.  The message though is not very clear about this, so we might want to consider changing the validation error message.  Should likely log a specification tracker item to discuss this.

**Comment by cjmyers** [comment]
10201 is done.  10214 is not possible.  Closing.
