### ISSUE TITLE
Add code to throw SBOL validation exceptions for these rules for Annotations 

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#307]
12201, 12202, 12203, 12204, 12205, 12206

**Comment by cjmyers** [comment]
I'm really not sure if these rules can be checked in libSBOLj, since I believe to violate them would prevent proper parsing of the file.

**Comment by cjmyers** [comment]
Only 12204 and 12205 are possible to check.

**Comment by cjmyers** [comment]
Decided not to check those either as they would be difficult to check.
