### ISSUE TITLE
Invalid RDF file skips validation rule 11406

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#310]
The attached test file has a SequenceConstraint: http://sbols.org/CRISPR_Example/EYFP_gene/EYFP_gene_constraint/1.0. Its object and subject point to the same component http://sbols.org/CRISPR_Example/EYFP_gene/EYFP_cds/1.0. But no exception of rule 11406 is thrown by the library.
[sbol-11406.txt](https://github.com/SynBioDex/libSBOLj/files/168140/sbol-11406.txt)

**Comment by cjmyers** [comment]
This should be fixed now.

**Comment by zgzn** [comment]
It is fixed now. Closing.
