### ISSUE TITLE
SBOLValidator expects displayIds for SBOLObjects to be the unique

### ISSUE THREAD

**Issue by hplahar** [SynBioDex/libSBOLj#32]
If two subcomponents have different URIs, assigning the same displayId causes an assertion failure in SBOLValidatorImp. According to the spec, displayIds are meant to be human readable, which typically does not imply uniqueness.

As an example, when converting the following genbank features:

 FEATURES             Location/Qualifiers
     gene            10..20
                     /label="AXL2"
     CDS             10..21
                     /label="AXL2"

assigning the label value to the displayId is considered invalid SBOL

**Comment by cjmyers** [comment]
Display ids are no longer required to be unique.
