### ISSUE TITLE
GenBank conversion to SBOL 2.0 ArrayOutOfBounds issue

### ISSUE THREAD

**Issue by 16zzundel5** [SynBioDex/libSBOLj#322]
stationarysalesman commented 7 days ago
:::::::::::::::::::::::::
When converting GenBank to SBOL 2.0 there is an issue with array bounds. Stack trace:

java.lang.ArrayIndexOutOfBoundsException: 7
at org.sbolstandard.core2.GenBank.read(GenBank.java:750)
at org.sbolstandard.core2.GenBank.read(GenBank.java:598)
at org.sbolstandard.core2.GenBank.read(GenBank.java:578)
at org.sbolstandard.core2.GenBank.read(GenBank.java:563)
at org.sbolstandard.core2.SBOLValidate.main(SBOLValidate.java:925)
7
Validation failed.

Following the error we see on line 750 in GenBank.java:
annotation = new Annotation(new QName(gbNamespace,"date",gbPrefix),strSplit[7]); 

The first line of my GenBank only had 5 instances of whitespace, against which the pattern was matching on line 739:
String[] strSplit = strLine.split("\\s+");

So this hard-coded string split is causing issues, since not all GenBank files have the same number of whitespace-delineated fields on line one.
:::::::::::::::::::::::::
Moved from SBOL-Validator issue tracker

**Comment by cjmyers** [comment]
I believe this is now fixed.  Please check.
