### ISSUE TITLE
checkReadOnly should throw SBOLConversionException instead of SBOLValidationException

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/libSBOLj#333]
The checkReadOnly method in SBOLDocument should throw a SBOLConversionException here, as this exception does not fall into violation of any SBOL validation rules.

**Comment by cjmyers** [comment]
I no longer think we need this method.  I’ve removed this method and all its uses and all the implied throws and related javadoc comments.

I also changed getPersistentIdentity() to return the identity when it is not set to make sure children can have a PI to build their compliant URI off of.

**Comment by cjmyers** [comment]
Done
