### ISSUE TITLE
Update JavaDocs for 2.1 Release

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#334]

**Comment by michael13162** [comment]
SBOLDocument.setDefaultURIprefix() could be more descriptive.  For example, "any objects created from now on will have *** as its URI prefix".

**Comment by michael13162** [comment]
Instead of "Represents the SBOL Component data model", could be better phrased with "Represents a Component object in the SBOL data model".

**Comment by michael13162** [comment]
CD.getSortedComponents() should go into more detail on how it's determining order (SA, SC, Location), rather than what the order means.

**Comment by michael13162** [comment]
CD.getImpliedNucleicAcidSequence() should go into how this Sequence is determined.  For example, the user doesn't know that the first thing this method does is look at the current sequence to determine the length/how many unknown bases there are.

**Comment by michael13162** [comment]
Formatting is inconsistent.  For example:
Removes the given sequence from this SBOLDocument object's list of Sequence instances. 

Also, sometimes data model objects are italicized, capitalized, or plain lowercase.  There doesn't seem to be a convention all the documentation follows.

**Comment by zgzn** [comment]
These issues should now be updated. Please check.
