### ISSUE TITLE
Create a simple demo project

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#343]
1. Take the Eclipse/Maven project produced by the example and check it into GitHub so somebody can just clone it to get started.  Here is an example of what I mean from one of my other projects: https://github.com/Protelis/Protelis-Demo

2. Change the item from "A code example for constructing a CRISPR circuit can be found [here]" to "An example libSBOLj project can be found [here], along with [documentation]"

**Comment by zgzn** [comment]
The project source is on Github. The webpage was also updated to include links to this project and its document, separated as two bullet items. I think this issue can be closed now.

**Comment by cjmyers** [comment]
Done
