### ISSUE TITLE
JavaDoc for Interaction createParticipation method

### ISSUE THREAD

**Issue by mehersam** [SynBioDex/libSBOLj#360]
In the javaDoc for the Interaction class createParticipant method, the participantId javaDoc says 'specify precisely one FunctionalComponent object that plays the designated role in its parent Interaction object' 

Should this say that 'precisely one _ComponentDefinition_ object that plays the designated role in its parent Interaction object'?

**Comment by cjmyers** [comment]
It is a little subtle.  For the createParticipation method which takes a URI, it is indeed a URI for a functionalComponent.  For the ones that take a String, it is either the displayId for a functionalComponent OR if createDefaults is active, then it will create a functionalComponent with that displayId that instantiatiates a ComponentDefinition with that displayId.

**Comment by cjmyers** [comment]
Updated javadoc.
