### ISSUE TITLE
SequenceAnnotation roleIntegration method JavaDoc

### ISSUE THREAD

**Issue by mehersam** [SynBioDex/libSBOLj#374]
The javadoc for the roleIntegration method says "returns the role integration for this object"

What is a role integration? It would be good to include what it means in the javadoc

**Comment by cjmyers** [comment]
This is part of SBOL 2.1.  The recent approved SEP.  

Chris

**Comment by drdozer** [comment]
Genetically, does the javadoc link to the relevant spec location?

**Comment by cjmyers** [comment]
The reason this one was confusing to Meher was that it is not in the specification.  This is the new field added by the recently agreed on SEP#004.  We definitely need to get the spec updated as soon as possible.
