### ISSUE TITLE
Change toString methods to leverage super toString methods

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#381]
Change all toString methods to start by calling super class toString methods.

**Comment by zgzn** [comment]
This should be done now. Probably needs testing.

**Comment by mehersam** [comment]
Tested toString methods for all classes. In SequenceConstraint, toString() method, if getRestiction().toString() is used instead of the private variable directly, then RestrictionType toString() method can also be called.

**Comment by zgzn** [comment]
Made the suggested changes. Please check.

**Comment by mehersam** [comment]
Looks good. Tests are also there in parallel with the new changes.
