### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by drdozer** [SynBioDex/libSBOLj#404]
I've found something that's triggering a NPE. The stacktrace is:

```
[info]                  java.lang.NullPointerException
[info] org.sbolstandard.core2.SBOLReader.parseComponent(SBOLReader.java:2165)
[info] org.sbolstandard.core2.SBOLReader.parseComponentDefinitions(SBOLReader.java:1455)
[info] org.sbolstandard.core2.SBOLReader.readTopLevelDocs(SBOLReader.java:821)
[info] org.sbolstandard.core2.SBOLReader.read(SBOLReader.java:522)
[info] org.sbolstandard.core2.SBOLDocument.read(SBOLDocument.java:2257)
[info] org.sbolstandard.core2.SBOLFactory.read(SBOLFactory.java:1471)
```

The test input that triggers this is attached.

Using version libSBOLj 2.1.0

[test.xml.txt](https://github.com/SynBioDex/libSBOLj/files/587470/test.xml.txt)

**Comment by cjmyers** [comment]
This is not legal SBOL.  A component needs to be formatted like this:

    <sbol:component>
      <sbol:Component rdf:about="http://seva.cnb.csic.es/cd/pSEVA231/FseI">
        <sbol:persistentIdentity rdf:resource="http://seva.cnb.csic.es/cd/pSEVA231/FseI"/>
        <sbol:displayId>FseI</sbol:displayId>
        <sbol:access rdf:resource="http://sbols.org/v2#public"/>
        <sbol:definition rdf:resource="http://seva.cnb.csic.es/cd/FseI"/>
      </sbol:Component>
    </sbol:component>

Of course, a Null pointer is the wrong message, it should clearly give a SBOLValidationException, so this is indeed a bug.

**Comment by drdozer** [comment]
Understood. But bad data should ideally lead to a useful error, not a NPE.

**Comment by cjmyers** [comment]
Agreed, this is why I said this is a real bug.

**Comment by cjmyers** [comment]
I think I’ve checked in a fix for this.  Please test it.

Thanks,

Chris
