### ISSUE TITLE
Corrections to Maven instructions for using libSBOLj

### ISSUE THREAD

**Issue by minnatwang** [SynBioDex/libSBOLj#414]
Some parts of the [Maven instructions](http://sbolstandard.org/wp-content/uploads/2016/09/GettingStartedTutorial_libSBOLj.pdf) are unclear or don't cover steps that the user encounters in Eclipse. I'd suggest the instructions be updated as follows:

* Step 4 of Getting Started section - say "check" instead of "select"
* Step 5 of Getting Started section - clarify whether or not the user should restart Eclipse when prompted to by the application (when I worked through the instructions, I didn't restart and it worked fine)
* Creating a New Project section - the instructions are missing a window screenshot between "Create a Maven project" and "Select an archetype"
* Formatting pom.xml section - specify that the user needs to click on the rightmost tab on the bottom of the screen to see the right window
* Formatting pom.xml section - explain the differences between the temporary and permanent fix before beginning to instruct the user to go through the temp fix
* Editing pom.xml section - right now copying and pasting directly from the PDF results in the line #s being copied as well, which means the user has to delete all the line numbers one-by-one after pasting the code into Eclipse; change the format of the PDF so this doesn't happen
* Adding SBOL dependency section - after adding dependencies, the user needs to right click on the project and click Maven > Update Project; on the window that comes up "Force Update of Snapshots/Releases" must be checked

**Comment by mehersam** [comment]
Fixed everything except for bullets 5 and 6. Does anyone know how to keep the line numbers but have them also excluded in the pdf? Would it be better to just remove the line numbers?

**Comment by mehersam** [comment]
Fixed except bullet 5. Wasn't sure how to remove the line numbers and keep formatting in LaTex.

**Comment by mehersam** [comment]
done.
