### ISSUE TITLE
module mapsto remote

### ISSUE THREAD

**Issue by drdozer** [SynBioDex/libSBOLj#419]
I'm not sure that the remote fields of mapsto in module in a ModuleDefinition are being correctly validated. Please find attached an xml file that validates, but where the remote fields are faulty.
[text.xml.txt](https://github.com/SynBioDex/libSBOLj/files/627772/text.xml.txt)

**Comment by cjmyers** [comment]
When I run it through the validator, it does fail for me, see report below.  This includes several complaints about Remote properties of MapsTos.

Validation failed.
sbol-10604: The URI contained by the definition property MUST refer to a ComponentDefinition object.
Reference: SBOL Version 2.1.0 Section 7.7.1 on page 26
: http://shortbol.ico2s.org/tutorial/modules/4-complete#ToggleSwitch/OurTetR
sbol-10604: The URI contained by the definition property MUST refer to a ComponentDefinition object.
Reference: SBOL Version 2.1.0 Section 7.7.1 on page 26
: http://shortbol.ico2s.org/tutorial/modules/4-complete#ToggleSwitch/OurLacI
sbol-11703: The URI contained by the definition property of Module MUST refer to a ModuleDefinition.
Reference: SBOL Version 2.1.0 Section 7.9.1 on page 41
: http://shortbol.ico2s.org/tutorial/modules/4-complete#ToggleSwitch/syntheticId_6
sbol-10809: If a MapsTo is contained by a Module, then the remote property of the MapsTo MUST refer to a FunctionalComponent in the ModuleDefinition that is referenced by the definition property of the Module.
Reference: SBOL Version 2.1.0 Section 7.7.3 on page 29
: http://shortbol.ico2s.org/tutorial/modules/4-complete#ToggleSwitch/syntheticId_6/syntheticId_8
sbol-10809: If a MapsTo is contained by a Module, then the remote property of the MapsTo MUST refer to a FunctionalComponent in the ModuleDefinition that is referenced by the definition property of the Module.
Reference: SBOL Version 2.1.0 Section 7.7.3 on page 29
: http://shortbol.ico2s.org/tutorial/modules/4-complete#ToggleSwitch/syntheticId_6/syntheticId_7
sbol-11703: The URI contained by the definition property of Module MUST refer to a ModuleDefinition.
Reference: SBOL Version 2.1.0 Section 7.9.1 on page 41
: http://shortbol.ico2s.org/tutorial/modules/4-complete#ToggleSwitch/syntheticId_9
sbol-10809: If a MapsTo is contained by a Module, then the remote property of the MapsTo MUST refer to a FunctionalComponent in the ModuleDefinition that is referenced by the definition property of the Module.
Reference: SBOL Version 2.1.0 Section 7.7.3 on page 29
: http://shortbol.ico2s.org/tutorial/modules/4-complete#ToggleSwitch/syntheticId_9/syntheticId_11
sbol-10809: If a MapsTo is contained by a Module, then the remote property of the MapsTo MUST refer to a FunctionalComponent in the ModuleDefinition that is referenced by the definition property of the Module.
Reference: SBOL Version 2.1.0 Section 7.7.3 on page 29
: http://shortbol.ico2s.org/tutorial/modules/4-complete#ToggleSwitch/syntheticId_9/syntheticId_10 <http://shortbol.ico2s.org/tutorial/modules/4-complete#ToggleSwitch/syntheticId_9/syntheticId_10>

**Comment by cjmyers** [comment]
Did you perhaps select Allow Incomplete Documents?  If you do, then this validates because in this case you are not required to dereference remote MapsTos, since the ModuleDefinitions may not be in the document.

**Comment by cjmyers** [comment]
Matthew: can you comment if this is still an issue?

**Comment by cjmyers** [comment]
closing
