### ISSUE TITLE
Add use of validator and comparison functions to the tutorial

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#420]
Would be good to add the use of the SBOL validation at the end of the tutorial, followed by a run of the comparison tool with a completed solution file.

**Comment by cjmyers** [comment]
SBOLValidate.validateSBOL(doc, true, true, true);
		if (SBOLValidate.getNumErrors() > 0) {
			for (String error : SBOLValidate.getErrors()) {
				System.out.println(error);
			}
			return;
		}
		// TODO: uncomment to compare with a "golden" version of the RepressionModel.xml
		//SBOLDocument doc2 = SBOLReader.read(<path of RepressionModel.xml>);
		//SBOLValidate.compareDocuments("Mine", doc, "Solution", doc2);

**Comment by mehersam** [comment]
Done. Added link to comparison file
