### ISSUE TITLE
Change all SBOL2 test files to .xml

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#422]
Use the .xml extension for all SBOL files in our test suite.

**Comment by mehersam** [comment]
done.

**Comment by cjmyers** [comment]
Looks good except please change the directory that was RDF (now XML) to RDF.  This is the type of representation used in these tests.  Have a look at the files, they are quite different.

**Comment by mehersam** [comment]
Okay, should be fixed now.

**Comment by mehersam** [comment]
Okay, should be fixed now. @cjmyers could you please let me know if the changes made are correct? Thank you!

**Comment by cjmyers** [comment]
Looks good closing.

**Comment by cjmyers** [comment]
Looks good closing.
