### ISSUE TITLE
Fix CRISPR code (RepressionModel.java) examples

### ISSUE THREAD

**Issue by minnatwang** [SynBioDex/libSBOLj#425]
In [libSBOLj_demo](https://github.com/SynBioDex/libSBOLj-Demo/blob/master/src/main/java/mySBOLexamples/crispr/RepressionModel.java) and [libSBOLj examples](https://github.com/SynBioDex/libSBOLj/tree/develop/examples/src/main/java/org/sbolstandard/core2/examples) (and wherever else the same RepressionModel.java file and its output, RepressionModel.rdf, is), make these changes:

* replace all instances of "CRPb_characterization_Circuit" to "CRPb_characterization_circuit"

**Comment by mehersam** [comment]
Changed in[ libSBOLj examples](https://github.com/SynBioDex/libSBOLj/tree/develop/examples/src/main/java/org/sbolstandard/core2/examples), but need permission for [libSBOLj_demo](https://github.com/SynBioDex/libSBOLj-Demo)

**Comment by cjmyers** [comment]
Should have it now, or received an invitation.  Please try.

**Comment by cjmyers** [comment]
Should have it now, or received an invitation.  Please try.

**Comment by mehersam** [comment]
Done.
