### ISSUE TITLE
libSBOL compiling command

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/libSBOLj#430]
In http://synbiodex.github.io/libSBOL/installation.html, the installation instruction indicated that to compile example c++ file(s) with the  libSBOL library, I should use this command to compile the example file(s):  g++ -std=c++11 -I../libSBOL/source -I/usr/local/include/raptor2 -L/usr/local/lib -lraptor2 -lsbol client_app.cpp -o client_app

This command line gave me this error:

<img width="1130" alt="libsbolc_err" src="https://cloud.githubusercontent.com/assets/7537729/21658537/48629af8-d284-11e6-9949-cf0cbb781827.png">

However, if I remove the -lsbol option and run with this command, I got could print out a simple hello message to the terminal.

g++ -std=c++11 -I../libSBOL/source -I/usr/local/include/raptor2 -L/usr/local/lib -lraptor2 client_app.cpp -o client_app

If I continue to use this command line to compile my example code with sbol objects, I get the same error from shown in the above image. 

Here is a small sample code that I used to compile:

#include "sbol.h"
#include <iostream>
using namespace std;
using namespace sbol;

int main()
{
    int passed = 0;
    int failed = 0;
    cout<< "hello";
    
//    Document& doc = *new Document();

//     cout << "Passed: " << passed << endl;
//     cout << "FAILED: " << failed << endl;
    
}

**Comment by cjmyers** [comment]
Incorrect issue tracker
