### ISSUE TITLE
Adding an annotation with the dcterms prefix breaks the namespace list

### ISSUE THREAD

**Issue by udp** [SynBioDex/libSBOLj#442]
I added an annotation for "modified" using a QName with prefix `http://purl.org/dc/terms/` and local part `modified`.  libSBOLj then gave me an invalid XML file.

    <?xml version="1.0" ?>
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/dc/terms/" xmlns:sbol="http://sbols.org/v2#" xmlns:prov="http://www.w3.org/ns/prov#">
      <sbol:ComponentDefinition rdf:about="http://synbiohub.org/swissprot/P0C8N0/1">
        <sbol:persistentIdentity rdf:resource="http://synbiohub.org/swissprot/P0C8N0"/>
        <sbol:displayId>P0C8N0</sbol:displayId>
        <sbol:version>1</sbol:version>
        <prov:wasDerivedFrom rdf:resource="http://www.uniprot.org/uniprot/P0C8N0"/>
        <dcterms:title>Lectin-like protein BA14k</dcterms:title>
        <created>2009-01-20</created>
        <modified>2016-11-02</modified>
        <sbol:type rdf:resource="http://www.biopax.org/release/biopax-level3.owl#Protein"/>

As you can see, it's _removed_ the xmlns:dcterms but still uses it in dcterms:title (so this is actually invalid XML), and for some reason it's decided to make my annotation namespace the default namespace using xmlns=.

**Comment by cjmyers** [comment]
My suspicion is that you confused prefix with namespace.  The prefix should be the alias for the namespace.  This may have caused some confusion in the code.

**Comment by udp** [comment]
Ahh, yes, it's actually a QName.  It was late...

I don't know why I should know anything about QNames as a user, though.  The prefixes are an implementation detail.

**Comment by cjmyers** [comment]
A developer using annotations better know something about QNames or they should not be creating annotations.

**Comment by udp** [comment]
That wasn't what I meant - I mean that at the point of adding an annotation, all I should care about is the URI of the annotation.

I'm reopening this because I'm still confused; the constructor of QName is:

    QName(String namespaceURI, String localPart)

and I'm constructing it as

    new QName("http://purl.org/dc/terms/", "modified")

why is this not correct?

**Comment by cjmyers** [comment]
The library currently organizes namespaces into a HashMap indexed on the namespace URI.  This means that each URI is only allowed to have one entry and therefore can only have one prefix.  It is though legal XML to have multiple prefixes point to the same URI.  Either this map needs to use both the URI and prefix for the key OR when writing back out, it should map all tags to use the same prefix regardless of which prefix they had when being read in.

**Comment by udp** [comment]
It's possible to reproduce this just by loading an XML file that has its own namespace for dc and re-serializing it.  libSBOLj will delete the custom namespace, and then continue to use the user namespace in the XML even though it's not defined (= invalid XML).

**Comment by udp** [comment]
I think that:

* all the annotation functions should take URIs instead of QNames as the annotation "name"
* an SBOLDocument should keep a mapping of prefix -> URIs and use this at serialization to provide "friendly" prefixes
* if no prefix is found in this mapping, use ns0, ns1 etc. like sboljs does

**Comment by cjmyers** [comment]
Unfortunately likely not this simple.  The trouble is Annotations are stored using the NamedProperty class from Goksel/Matthew’s sbol-data.  This object requires a full QName upon construction.  To further make things difficult, these objects are immutable, so it is not possible to later change the prefix when the Annotation is added to a document and the namespaces are known.

The only viable solution I see is to rebuild the Annotation class to not use the NamedProperty class at all, but instead only create the NamedProperty for serialization.

Someone will need to remind me again why immutable objects are a good thing…ugh

**Comment by udp** [comment]
>  The only viable solution I see is to rebuild the Annotation class to not use the NamedProperty class at all, but instead only create the NamedProperty for serialization.

This sounds sensible.

**Comment by cjmyers** [comment]
I fixed this issue I think.  Namespaces are now allowed to have multiple different prefixes.  Not ideal, since you could get a lot of extra prefixes, but at least it does not create invalid XML.
