### ISSUE TITLE
SynBioHubFrontend submit methods should have API cleaned up

### ISSUE THREAD

**Issue by zachzundel** [SynBioDex/libSBOLj#483]
Collections should be removed as no longer supported.

Overwrite_merge should be changed to a Boolean (possible changes in SynBioHub to support too).

Should have a submit method that takes just id, overwrite, and doc/file to allow for submission into an existing collection (should make sure error checking that it exists on SynBioHub side).

**Comment by zachzundel** [comment]
Put in new method signatures, deprecate but do not remove old ones.

**Comment by cjmyers** [comment]
All done except error checking about existing collection, though it still does throw such an error.

**Comment by cjmyers** [comment]
Done
