### ISSUE TITLE
SBOLDocument. addNamespaceBinding(NamespaceBinding)

### ISSUE THREAD

**Issue by eoberortner** [SynBioDex/libSBOLj#487]
I'm always running into the exception:
sbol-10105: An SBOL document MUST be serialized as a well-formed RDF/XML file that adheres to the grammar defined by: “https://www.w3.org/TR/rdf-syntax-grammar/” 

Please, could anybody let me know how to set the namespace properly?
Currently, I'm just using the default namespace

**Comment by cjmyers** [comment]
You should never call addNamespaceBinding.  This is a package private method.  You should be using addNamespace.  

The && is correct.  Namely, a namespace is required to end in a delimiter (#, :, or /).

**Comment by eoberortner** [comment]
I do not call the addNamespaceBinding method. I was wrong with the logical OR. it should be logical AND as it is. 
However, I'm still running into the exception: 
sbol-10105: An SBOL document MUST be serialized as a well-formed RDF/XML file that adheres to the grammar defined by: “https://www.w3.org/TR/rdf-syntax-grammar/” 
Reference: SBOL Version 2.1.0 Section 10 on page 58

**Comment by cjmyers** [comment]
Can you give me the sample code where you call addNamespace?

**Comment by eoberortner** [comment]
Attached the code. it's caused when calling the  createAnnotation method (line 60)

[sbol-issue.txt](https://github.com/SynBioDex/libSBOLj/files/1258291/sbol-issue.txt)

**Comment by eoberortner** [comment]
also, here is my stacktrace:
Exception in thread "main" org.sbolstandard.core2.SBOLValidationException: sbol-10105: An SBOL document MUST be serialized as a well-formed RDF/XML file that adheres to the grammar defined by: “https://www.w3.org/TR/rdf-syntax-grammar/” 
Reference: SBOL Version 2.1.0 Section 10 on page 58
	at org.sbolstandard.core2.SBOLDocument.addNamespaceBinding(SBOLDocument.java:2170)
	at org.sbolstandard.core2.SBOLDocument.addNamespace(SBOLDocument.java:2151)
	at org.sbolstandard.core2.Identified.addNamespace(Identified.java:463)
	at org.sbolstandard.core2.Identified.addAnnotation(Identified.java:530)
	at org.sbolstandard.core2.Identified.createAnnotation(Identified.java:366)
	at org.sbolstandard.assembly.demo.SBOLTest.main(SBOLTest.java:60)

**Comment by cjmyers** [comment]
Try adding a delimiter (/, #, : ) at the end of string in URI_PREFIX

**Comment by eoberortner** [comment]
OK, the following command works:
cd.createAnnotation(new QName(URI_PREFIX + "#", "derivation", "derivation"), "purchase");

thanks for your help! interesting behavior though.

**Comment by eoberortner** [comment]
I'll just add the '#' sign to the URI_PREFIX constants. that should solve the issue. 

thanks again!

**Comment by cjmyers** [comment]
The reason we need to have the delimiter is namespaces without them cause all kinds of problems especially when serialized as anything other than XML.

**Comment by eoberortner** [comment]
just out of curiosity, could the library add a delimiter if non is provided?

**Comment by cjmyers** [comment]
Perhaps, but it would not know the correct one.  It is often #, but sometimes /.
