### ISSUE TITLE
create with nulls "duplication" validation errors

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/libSBOLj#500]
When I accidentally invoke a "create" on missing / null material, it provideds a misleading error, invoking rule 10202 (duplication) rather than just complaining about a null.

**Comment by cjmyers** [comment]
Can you give more detail?  Which create method and which value was null?  Sounds like the wrong validation error is being reported.

**Comment by jakebeal** [comment]
ModuleDefinition.createModule, called with a faulty displayId string

**Comment by cjmyers** [comment]
Ah, I see the problem.  DisplayIds are not “technically” required.  So, the code only validates that the displayId is valid, if it is not null.  Therefore, it creates a URI with a null displayId.  Likely this ends up with a URI that conflicts with an already created URI (likely the parent object actually).

However, when you are creating a compliant URI, the displayId is indeed required.  Therefore, I’ve added a check for null when creating a compliant URI, and it now throws 10204 which is an invalid displayId error.

This is in the provO branch, which I hope to fold in soon.

**Comment by cjmyers** [comment]
This fix should be in the master branch now.  @jakebeal can you verify this works now?
