### ISSUE TITLE
Add support for the Attachment class

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/libSBOLj#507]
See:
https://github.com/SynBioDex/SEPs/blob/master/sep_018.md

**Comment by IgorDurovic** [comment]
I had some issues with git so the commits on the Attachment branch aren't very well organized. Also, it looks like my first commit deleted some files (no idea why). That might have to be reverted. The attachment class itself and support for attachment in TopLevel was completed. Validation, SBOLDoc, SBOLReader, and SBOLWriter still need to be updated.

**Comment by cjmyers** [comment]
Complete
