### ISSUE TITLE
createRecursiveCopy needs to follow all links

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/libSBOLj#527]
Specifically, createRecursiveCopy may not be copying over wasDerivedFroms or wasGeneratedBys.  As we said though, wasGenereratedBys should be copied over, but one could make the argument that wasDerivedFroms aren't necessary.

Also, Activity's have usages to derivations that are also not being copied.  This is necessary for the serialization of combinatorial derivations after enumeration.

**Comment by cjmyers** [comment]
It is now copying links in wasDerivedFrom/wasGeneratedBy.  Links via Entities in Usages already appear to be working.

**Comment by cjmyers** [comment]
@michael13162 is this working for you now?  If so, please close.
