### ISSUE TITLE
StringIndexOutOfBoundsException in SBOLValidate

### ISSUE THREAD

**Issue by zachzundel** [SynBioDex/libSBOLj#545]
I run into this issue on SBOLValidate:
![screenshot-2018-3-27 zach s synbiohub](https://user-images.githubusercontent.com/3093325/38011015-dc16804e-3218-11e8-981c-622819810e0b.png)

**Comment by cjmyers** [comment]
This is related to issue parsing GenBank LOCUS line which should be fixed now.
