### ISSUE TITLE
Flipping orientation with an all caps sequence creates N's. 

### ISSUE THREAD

**Issue by SamuelSauce** [SynBioDex/libSBOLj#564]
When flipping the orientation of a part that has an all caps sequence, the base pairs are usually changed to reflect their complementary base pair. When the method 'Sequence.reverseComplement()' is called, it does not recognize an all caps sequence, thus does not properly flip the sequence.

**Comment by cjmyers** [comment]
@SamuelSauce have you fixed this one?

**Comment by cjmyers** [comment]
Fixed by PR #567
