### ISSUE TITLE
GenBank exports lose names

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/libSBOLj#593]
(copy of https://github.com/SynBioHub/synbiohub/issues/944, per evaluation by @cjmyers )

GenBank exports come out with anonymous features. Here is an example:
https://synbiohub.org/public/igem/BBa_K808000/1
https://synbiohub.org/public/igem/BBa_K808000/1/BBa_K808000.gb

The SBOL knows the features are AraC, AraO, AraO1, and AraPromoter, but the GenBank loses that information.

I don't know just what the GenBank file should look like (not actually using GenBank much), but it should be able to round-trip from GenBank --> SBOL --> GenBank --> SBOL such that the two SBOL versions are identical.

**Comment by cjmyers** [comment]
GenBank -> SBOL -> GenBank -> SBOL should work fine.

What you are asking for here is different, you are asking for:

SBOL -> GenBank -> SBOL

This is an inherently lossy translation I’m afraid.

**Comment by jakebeal** [comment]
I am asking for GenBank -> SBOL -> GenBank -> SBOL (which can be validated by comparing the two SBOLs).  Right now, it is not working, per the bug listed.

**Comment by jakebeal** [comment]
Let's use the '/label' convention

**Comment by cjmyers** [comment]
Fixed
