### ISSUE TITLE
Some potential NPE bugs

### ISSUE THREAD

**Issue by JulyChen728** [SynBioDex/libSBOLj#601]
Hi all,
Our bug scanner has reported some NPE bugs.

1.The first bug is caused by the `return null` in function [getDescendantsOf()](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/EDAMOntology.java#L234) . A possible call chain is [getDescendantsOf()](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/EDAMOntology.java#L250) => [EDAMOntology.java#L311](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/EDAMOntology.java#L311) . A NullPointerException may take place at [EDAMOntology.java#L313](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/EDAMOntology.java#L313) , when the return value of method `getDescendantsOf()` invokes its `iterator` method.

Several similar statements are at [SequenceOntology.java#L329](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/SequenceOntology.java#L329) , [SequenceOntology.java#L296](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/SequenceOntology.java#L296) , [SystemsBiologyOntology.java#L331](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/SystemsBiologyOntology.java#L331) and [SystemsBiologyOntology.java#L348](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/SystemsBiologyOntology.java#L348) .

2.The second bug is caused by the `return null` in function [getId()](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/SystemsBiologyOntology.java#L154) . A possible call chain is [SystemsBiologyOntology.java#L218](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/SystemsBiologyOntology.java#L218) =>[SystemsBiologyOntology.java#L229](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/SystemsBiologyOntology.java#L229) . And a NPE may [take place](https://github.com/SynBioDex/libSBOLj/tree/master/core2/src/main/java/org/sbolstandard/core2/SystemsBiologyOntology.java#L229) when the parameter `stanzaId` invokes its method `trim()` since it may be `null` .

Thanks.

**Comment by cjmyers** [comment]
Thanks.  All good catches.  What is the name of your bug scanner?

**Comment by cjmyers** [comment]
Fixed by PR #602
