### ISSUE TITLE
getRootComponentDefinitions() does not treat the Variants in a Variable Component as a child Component of a Component Definition

### ISSUE THREAD

**Issue by ImperialiGEM2020** [SynBioDex/libSBOLj#613]
getRootComponentDefinitions() should treat the Variants of a Variable Component as child Components of the template Component Definition, and remove the Component Definitions describing these Variants from the set of Root Component Definitions.

Currently, the function only checks Component Definitions for its Components. However, for a Component Definition describing a template for a Combinatorial Derivation, the variable Component is indicated with a 'placeholder' Component. While the function will remove the Component Definition of this 'placeholder' Component, it does not remove the Component Definitions of its corresponding Variants, which it rationally should.

This causes the set of Root Component Definitions to include Component Definitions that are indirectly referenced by a child Component.

For example, this causes the promoters in the violacein combinatorial derivation example taken from the paper "Specifying Combinatorial Designs with the Synthetic Biology Open Language (SBOL)" to be shown when displaying only root Component Definitions.

![image](https://user-images.githubusercontent.com/60446814/87363863-ff149b80-c569-11ea-8dd5-13019a48e755.png)

**Comment by cjmyers** [comment]
Thanks for the detailed bug report.  I've updated getRootComponentDefinitions() in libSBOLj to exclude the variant ComponentDefinitions.
