### ISSUE TITLE
create<Foo> shouldn't ever return null

### ISSUE THREAD

**Issue by drdozer** [SynBioDex/libSBOLj#78]
I was calling createComponentDefinition with a bad display ID. Instead of telling me I'd been stupid (e.g. by raising an illegal argument exception telling my my display ID was bad), it returned null. Later on, when I dereferenced that return value, I got a null pointer exception.

Please don't return nulls to flag failure. Please raise exceptions.

**Comment by cjmyers** [comment]
I believe this one has been fixed.
